version: "3"
services: 
  node-app-uno:
    container_name: hw-uno
    image: albertcontra/app-node-prueba:v1.2.0
    depends_on: 
     - mongodb-server
    env_file:
     - ./.env
    ports: 
      - "3010:3010"
      
  node-app-dos:
    container_name: hw-dos
    image: albertcontra/app-node-prueba:v1.2.0
    depends_on: 
     - mongodb-server
    env_file:
     - ./.env
    ports: 
      - "3020:3010"

  mongodb-server:
    container_name: hw-mongo
    hostname: hwMongo
    image: mongo:4.4-bionic
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password